Feat/adding parameterization details to asset card
sovity/edc-ui pull request #366
Opened 2023-07-18 12:29 UTC by AnurosePrakash

# Pull Request

Adding viewing of parameterization options to Asset details

## How Has This Been Tested?
 with fake backend

## PR is blocked by

-   [ ] blocked by #https://github.com/sovity/edc-ui/issues/357

# Checklist

-   [ ] I have **formatted the title** correctly and precisely
-   [ ] My code follows the **style guidelines** of this project
-   [ ] I have performed a **self-review** of my own code
-   [ ] I have **commented** my code, particularly in hard-to-understand areas and public classes/methods
-   [ ] I have made corresponding changes to the **documentation**
-   [ ] My changes generate **no new warnings** (performed checkstyle check locally)
-   [ ] I have added **tests that prove my fix** is effective or that my feature works
-   [ ] New and existing unit **tests pass locally** with my changes
-   [ ] Any dependent **changes have been merged** and published in downstream modules
-   [ ] I have added/updated **copyright headers**

2023-07-19 14:28 UTC, SaadEGI commented on src/app/component-library/catalog/asset-detail-dialog/asset-property-grid-group-builder.ts
> +        httpProxiedQueryParams: asset.httpProxyQueryParams
const proxyDetails = [
    'httpProxyMethod', 
    'httpProxyBody', 
    'httpProxyPath', 
    'httpProxyQueryParams'
]; anyway to use an array like this to check both conditions?

2023-07-19 14:28 UTC, SaadEGI commented on src/app/component-library/catalog/asset-detail-dialog/asset-property-grid-group-builder.ts
Lines

2023-07-19 14:58 UTC, SaadEGI requested changes

2023-10-10 08:33 UTC, richardtreier commented
closed in favor of https://github.com/sovity/edc-ui/pull/511

2023-10-10 08:33 UTC, closed without merging