feat: Disabling login polling in broker ui
sovity/edc-ui pull request #368
Opened 2023-07-19 11:23 UTC by AnurosePrakash

# Pull Request

Disabling login polling in broker ui

## How Has This Been Tested?

With mock backend

## PR is blocked by

-   [ ] blocked by #https://github.com/sovity/edc-ui/issues/360

# Checklist

-   [ ] I have **formatted the title** correctly and precisely
-   [ ] My code follows the **style guidelines** of this project
-   [ ] I have performed a **self-review** of my own code
-   [ ] I have **commented** my code, particularly in hard-to-understand areas and public classes/methods
-   [ ] I have made corresponding changes to the **documentation**
-   [ ] My changes generate **no new warnings** (performed checkstyle check locally)
-   [ ] I have added **tests that prove my fix** is effective or that my feature works
-   [ ] New and existing unit **tests pass locally** with my changes
-   [ ] Any dependent **changes have been merged** and published in downstream modules
-   [ ] I have added/updated **copyright headers**

2023-07-19 14:59 UTC, SaadEGI commented on src/app/app.component.ts
Lines

2023-07-19 15:00 UTC, SaadEGI commented on src/app/routes/connector-ui/connector-ui.component.ts
> +
Lines and struct

2023-07-19 15:00 UTC, SaadEGI requested changes

2023-08-10 07:09 UTC, SaadEGI commented on CHANGELOG.md
> +
newLines?

2023-08-10 07:10 UTC, SaadEGI submitted a review, later dismissed

2023-08-14 06:30 UTC, richardtreier approved these changes

2023-08-14 06:30 UTC, merged